///Constant names used in app ui
class UIConstants {
  ///Name of app_ui package
  static const String appUIPackageName = 'app_ui';

  /// list of various reasons for taking drugs
  static List<String> reasonsForTakingDrugs = [
    'Pain Relief',
    'Fever Reduction',
    'Inflammation Control',
    'Infection Treatment',
    'Allergy Relief',
    'Blood Pressure Regulation',
    'Diabetes Management',
    'Cholesterol Control',
    'Thyroid Regulation',
    'Seizure Control',
    'Psychiatric Disorders (Depression, Anxiety)',
    'Antibiotic Therapy',
    'Antiviral Therapy',
    'Antifungal Therapy',
    'Antiparasitic Treatment',
    'Cancer Treatment',
    'Bone Health (Calcium, Vitamin D)',
    'Iron Deficiency (Anemia)',
    'Gastrointestinal Disorders',
    'Respiratory Conditions',
    'Cardiovascular Health',
    'Hormone Replacement Therapy',
    'Contraception',
    'Fertility Treatment',
    'Immunization (Vaccination)',
    'Smoking Cessation',
    'Weight Management',
    'Sleep Disorders',
    'Substance Abuse Treatment',
    'Organ Transplant Immunosuppression',
    'Preventive Health (Aspirin for Heart Health)',
    'Attention Deficit Hyperactivity Disorder (ADHD)',
    'Migraine Prevention',
    'Osteoporosis Prevention',
    'Preoperative Medications',
    'Postoperative Pain Management',
    'Nutritional Supplements',
    'Detoxification',
    'Rheumatoid Arthritis',
    'Multiple Sclerosis',
    'Epilepsy',
    "Parkinson's Disease",
    "Alzheimer's Disease",
    'Gout Treatment',
    'Celiac Disease Management',
  ];

  ///  list of common ways to administer drugs
  static List<String> drugAdministrationMethods = [
    'Oral (Tablet, Capsule, Liquid)',
    'Sublingual (Under the tongue)',
    'Intravenous (IV) Injection',
    'Intramuscular (IM) Injection',
    'Subcutaneous (SC) Injection',
    'Inhalation (Inhaling as a vapor or aerosol)',
    'Topical (Cream, Ointment, Patch)',
    'Transdermal (Through the skin)',
    'Rectal (Suppository, Enema)',
    'Vaginal (Tablet, Cream, Suppository)',
    'Nasal (Nasal spray, Drops)',
    'Ophthalmic (Eye drops, Ointment)',
    'Otic (Ear drops)',
    'Intrathecal (Into the spinal canal)',
    'Intradermal (Into the dermal layer of skin)',
    'Sublingual/Buccal (Under the tongue or against the cheek)',
    'Intranasal (Through the nose)',
    'Intra-articular (Into a joint)',
    'Intracardiac (Into the heart)',
    'Intraperitoneal (Into the abdominal cavity)',
    'Intrapleural (Into the pleural space around the lungs)',
    'Intraosseous (Into the bone marrow)',
    'Intravaginal (Into the vagina)',
    'Intrarectal (Into the rectum)',
    'Intravesical (Into the bladder)',
    'Intramuscular Depot (Long-acting injectable)',
  ];

  ///list of possible drug intake intervals
  static List<String> drugIntakeIntervals = [
    'Once a Day',
    'Twice a Day',
    'Three Times a Day',
    'Four Times a Day',
    'Every 6 Hours',
    'Every 8 Hours',
    'Every 12 Hours',
    'Every 24 Hours',
    'Every Morning',
    'Every Evening',
    'Before Meals',
    'After Meals',
    'With Meals',
    'Before Bedtime',
    'Every Other Day',
    'Every Week',
    'Every Month',
    'As Needed',
    'PRN (Pro Re Nata - As Needed)',
    'Before Exercise',
    'After Exercise',
    'On an Empty Stomach',
    'With Food',
    'At the Same Time Every Day',
    'Before Breakfast',
    'Before Lunch',
    'Before Dinner',
    'Before Sleeping',
    'During the Night',
    'With Plenty of Water',
    'With Milk',
    'Sublingually (Under the tongue)',
    'Intramuscular Depot (Long-acting injectable)',
  ];

  /// A list of some of the common drugs that can be found in Nigeria
  static List<String> commonDrugsInNigeria = [
    'Paracetamol',
    'Ibuprofen',
    'Aspirin',
    'Amoxicillin',
    'Ciprofloxacin',
    'Co-trimoxazole',
    'Artemether/Lumefantrine',
    'Chloroquine',
    'Amlodipine',
    'Atenolol',
    'Enalapril',
    'Metformin',
    'Glibenclamide',
    'Insulin',
    'Omeprazole',
    'Ranitidine',
    'Metronidazole',
    'Doxycycline',
    'Nystatin',
    'Loratadine',
    'Cetirizine',
    'Ventolin (Salbutamol)',
    'Isoniazid',
    'Rifampicin',
    'Pyrazinamide',
    'Ethambutol',
    'Mebendazole',
    'Praziquantel',
    'Albendazole',
    'Folic acid',
    'Vitamin B complex',
    'Vitamin C',
    'Calcium carbonate',
    'Multivitamins',
    'Oral rehydration salts (ORS)',
    'Artemisinin-based Combination Therapies (ACTs)',
    'Azithromycin',
    'Dexamethasone',
    'Hydroxychloroquine',
    'Oseltamivir',
    'Warfarin',
    'Clopidogrel',
    'Atorvastatin',
    'Simvastatin',
    'Lisinopril',
    'Losartan',
    'Levothyroxine',
    'Citalopram',
    'Fluoxetine',
    'Lorazepam',
    'Olanzapine',
    'Risperidone',
    'Sertraline',
    'Tadalafil',
    'Sildenafil',
    'Levonorgestrel',
    'Ethinylestradiol',
    'Ceftriaxone',
    'Vancomycin',
    'Meropenem',
    'Amikacin',
  ];
}
