name: app_ui
description: App UI Component Library
publish_to: none

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_svg: ^2.0.5
  intl: any
  mockingjay: ^0.4.0
  palette_generator: ^0.3.3+2

dev_dependencies:
  build_runner: 
  flutter_gen_runner: ^5.3.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
   
flutter_gen:
  assets:
    package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true
