name: domain
description: Domain Component Library
publish_to: none

environment:
  sdk: '>=3.1.2 <3.10.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner:
  flutter_gen_runner: ^5.3.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^4.0.0+1

flutter:


